### ISSUE TITLE
Android compilation error due to missing kotlinVersion (with fix)

### ISSUE THREAD

**Issue by christophemarois** [OP-Engineering/op-sqlite#56]
**Describe the bug**

After upgrading `op-sqlcipher` from 1.0.8 to 1.0.18, compilation suddenly fails with:

```
A problem occurred configuring project ':op-engineering_op-sqlcipher'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':op-engineering_op-sqlcipher:classpath'.
      > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:null.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/null/kotlin-gradle-plugin-null.pom
          - https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/null/kotlin-gradle-plugin-null.pom
        Required by:
            project :op-engineering_op-sqlcipher
```

Manually specifying a `kotlinVersion` in `./android/build.gradle` fixes it.

```groovy
buildscript {
    ext {
        kotlinVersion="1.8.10"
    }
}
```

It looks like this line (which didn't change between .8 and .18 from what I'm seeing) used to work, but now returns `null`.

https://github.com/OP-Engineering/op-sqlite/blob/c5f492b025e13e8c381cf3bb3fc784ffb99b5adb/android/build.gradle#L9

I understand that this kind of gradle error can be a wack-a-mole, but putting this out here in case you have an idea what this is (or if it can help others).

Thank you for your time!

**Versions:**

- OS and version: **Android, N/A** (compilation error)
- op-sqlite version: **1.0.18** (latest at the time of writing)
- RN version: [e.g. 0.73.0] **0.72.4**
- New Architecture: [Yes/No] **No**

**Comment by ospfranco** [comment]
Thanks for noticing, turns out I made a mistake and ignored the gradle.properties file at some point. Will be fixed on the next version.
